### PR TITLE
Pass along options to upload as well

### PR DESCRIPTION
**Pull request by SimenB**
Needed to be able to set `public: true, gzip: true` etc.

https://googlecloudplatform.github.io/google-cloud-node/#/docs/storage/1.1.0/storage/file?method=createWriteStream

### CODE REVIEW

**Comment by SimenB** [comment]
Lint error (master is red as well)

**Comment by trygve-lie** [comment]
Good for now, but think we need to rethink how we pass these in.

**Comment by SimenB** [comment]
Agreed the current API is a bit clunky

**Comment by trygve-lie** [comment]
Published In version 1.0.0-beta.10

**Pull request merged**
